baseURL: https://alishir.github.io/
languageCode: en-us
title: "Brief Notes"
theme: "PaperMod"

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    contentDir: content/en
    weight: 1
    menu:
      main:
        - name: Tags
          url: "tags"
          weight: 10
        - name: Posts
          url: "post"
          weight: 5
  fa:
    languageName: "Persian"
    languagedirection: rtl
    contentDir: content/fa
    weight: 2
    title: "نُکَتْ"
    profileMode:
      enabled: true
      title: "علی شیروانی" # optional default will be site title
      subtitle: ""
      imageUrl: "" # optional
      imageTitle: "" # optional
      imageWidth: 120 # custom size
      imageHeight: 120 # custom size
      buttons:
        - name: "نوشته‌ها"
          url: "post"
        - name: "برچسب‌ها"
          url: "tags"
    menu:
      main:
        - name: نوشته‌ها
          url: "post"
          weight: 10        
        - name: برچسب‌ها
          url: "tags"
          weight: 20

  
params:
  env: production
  ShowReadingTime: true
  enableMissingTranslationPlaceholders: false
  ShowToc: true
  ShowBreadCrumbs: true
  profileMode:
    enabled: true
    title: "Ali Shirvani" # optional default will be site title
    subtitle: ""
    imageUrl: "" # optional
    imageTitle: "" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Posts
        url: "post"
      - name: Tags
        url: "tags"

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/alishir"
    - name: "twitter"
      url: "https://twitter.com/alishirv"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/ali-shirvani-37a031191/"
  
menu:
  main:
    - identifier: posts
      name: posts
      url: "posts"
      weight: 10
    - identifier: tags
      name: tags
      url: "tags"
      weight: 20
